name: Bug
description: File a bug report.
projects: ['panchapp/1']
type: Bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug in detail.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Describe the steps to reproduce the bug.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information that may be helpful.
    validations:
      required: false
