name: Feature
description: File a feature request.
projects: ['panchapp/1']
type: Feature
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the feature in detail.
    validations:
      required: true
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: Describe the requirements for the feature.
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Provide any additional information that may be helpful.
    validations:
      required: false
